# Setup
title: Kirk Library
tagline: Research at Centralia College
url:  https://ryerbanta.github.io/kirk-library
paginate: 1
baseurl: "/kirk-library"

# Theme
theme: jekyll-theme-slate


# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :title
relative_permalinks: true

